name: cloudheight docker images

on:
  pull_request:
    branches:
      - master
    paths:
      - 'application-assessment-repo/**'  
  push:
    branches:
      - master
    paths:
      - 'application-assessment-repo/**'   
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    name: Build images and push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # This step yields the following labels
      # - date+sha, e.g. 2023-01-19-da4692d,
      # - tag (if pushed).
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: kaytheog/cloudheight
          flavor: |
            latest=false
          tags: |
            type=raw,value={{date 'YYYY-MM-DD'}}-{{sha}}
            type=ref,event=tag
            type=edge

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./application-assessment-repo
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.ref == 'refs/heads/master' }}
          platforms: ${{ (github.ref == 'refs/heads/master') && 'linux/amd64,linux/arm64' || 'linux/arm64' }}
